ARG NODE_VERSION=20.14.0

FROM node:${NODE_VERSION}-slim

# Enable pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml files to the working directory
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile --shamefully-hoist

# Copy the rest of the application files
COPY . ./

# Define environment variables
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_ENV=development

# Expose the port the application will run on
EXPOSE 3000

# Start the development server
CMD [ "pnpm", "run", "dev" ]
